### ISSUE TITLE
bug: formatter custom arguments (findentArgs/fprettifyArgs) doesn't appear to work

### ISSUE THREAD

**Issue by irishismyname** [fortran-lang/vscode-fortran-support#1007]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I've added
```json
"fortran.formatting.findentArgs": ["-i4"],
```
to `.vscode/settings.json` in my project, but it doesn't seem to have any effect. To further test this I tried running `findent` independently with
```cmd
findent -i4 < variables.f90 > newvariables.f90
```
and it seems to work as expected.

To further test this, I changed my settings.json file to
```json
"fortran.formatting.findentArgs": ["-h"],
```

which I guess should have written the help content to my source file, but alas it did not.

### Expected Behaviour

`findent` arguments included in `Argumentsfortran.formatting.findentArgs` should be passed to `findent`.

### Version of Modern Fortran

v3.2.0

### Version of Visual Studio Code

v1.84.0

### Platform and Architecture

Windows 11 22621

### Additional Information

Using findent 4.2.6

**Comment by irishismyname** [comment]
Is there an easy way for me to see the actual `findent` call by the extension?

**Comment by irishismyname** [comment]
I switched to the pre-release version and enabled debug logging for VSCode, but the Modern Fortran Output Window isn't showing anything regarding `findent`. Is there a hidden option for logging level for this extension?

**Comment by gnikit** [comment]
Can you perform a document format and then copy-paste the contents of the Output pane here please.

**Comment by irishismyname** [comment]
## Log Level Setting
![image](https://github.com/fortran-lang/vscode-fortran-support/assets/34629432/03ee746d-f54f-42cf-90a0-e7ea886cf9e9)

## Output
![image](https://github.com/fortran-lang/vscode-fortran-support/assets/34629432/a48199fa-ea8a-42b1-8946-f10ae0b629aa)

I get the output above each time I save the file, but nothing shows up when I run format document. I think it's working because I set VSCode to indent with 2 spaces but `findent` defaults to 3 and I'm getting 3.

**Comment by irishismyname** [comment]
Update: `findentArgs` seem to be passed to `findent call, but it's only updating when I start VSCode. If I change the setting without restarting, it will not update.

**Comment by irishismyname** [comment]
When I tried to debug this version on my machine I made these observations:
1. When I modify my workspace `settings.json`, the [condition](https://github.com/fortran-lang/vscode-fortran-support/blob/427e8df2550a464bf504256a6d0acd4f31390ee3/src/lint/provider.ts#L53) to determine the change scope doesn't seem to evaluate `true` so the next line:
2. [`this.config = `](https://github.com/fortran-lang/vscode-fortran-support/blob/427e8df2550a464bf504256a6d0acd4f31390ee3/src/lint/provider.ts#L54) assignment to update the config never seems to run. Even so, I _think_ updating the config like this could be problematic as `this` might be an instance copy of `LinterSettings`.

**Comment by gnikit** [comment]
Thanks @irishismyname I noticed myself too, I will try and have a look (not sure when), but it's super annoying.
