### ISSUE TITLE
Erroneous syntax highlighting, when argument is called "function" or "procedure"

### ISSUE THREAD

**Issue by gnikit** [fortran-lang/vscode-fortran-support#207]
This is another edge case that the TextMate bundle did not account for. Some keywords should be escaped as when not matching their normal regex pattern.

![image](https://user-images.githubusercontent.com/16143716/101927006-df8ea700-3bcb-11eb-9927-af5a02b782cb.png)

```fortran
  interface set_scalar_field_from_python
    module procedure set_scalar_field_from_python_sp

    subroutine set_scalar_field_from_python(function, function_len, dim, &
         nodes, x, y, z, t, result, stat)
      use iso_c_binding, only: c_double, c_int, c_char
      implicit none
      integer(c_int), intent(in), value :: function_len
      character(kind=c_char, len=function_len) :: function
      integer(c_int), intent(in), value :: dim, nodes
      real(c_double), dimension(nodes), intent(in) :: x, y, z
      real(c_double), intent(in), value :: t
      real(c_double), dimension(nodes), intent(out) :: result
      integer(c_int), intent(out) :: stat
    end subroutine set_scalar_field_from_python
  end interface set_scalar_field_from_python
```

**Comment by pedro-ricardo** [comment]
Hello, please check if adding the `^\\s*` in the `begin` variable in `function-definition` scope as below solves your issue
### In here
```json
"function-definition": {
    "comment": "Funtion program unit. Introduced in the Fortran 1977 standard.",
    "name": "meta.function.fortran",
    "begin": "(?i)(?=([^'\";!\\n](?!\\bend))*\\bfunction\\b)",
    "end": "(?=[;!\\n])",
```
### Change
```json
    "begin": "(?i)(?=([^'\";!\\n](?!\\bend))*\\bfunction\\b)",
```
### To
```json
    "begin": "(?i)(?=([^'\";!\\n](?!\\bend))*^\\s*\\bfunction\\b)",
```

If it works, please consider adding the same fix to `subroutine-definition` in the same PR.

**Comment by gnikit** [comment]
@pedro-ricardo Do you know if we can somehow unittest the syntax highlighting? I fear that in fixing one thing we might break another

**Comment by pedro-ricardo** [comment]
When debugging the highlights I use the `editor.action.inspectTMScopes` to check if the word is in the correct scope and if not why it ended in a different scope.
So I suppose it is possible to create an example file, just like the one used in the symbol check, that will verify if the words are in the scope they should.

But since I've only changed the regex stuff in the extension so far, I have no knowledge of how the typescript files work inside it.

Maybe you should create another issue with this feature request. When this background of the test is done I imagine that it will be easier to add more and more cases for it to check.

**Comment by gnikit** [comment]
> Hello, please check if adding the `^\\s*` in the `begin` variable in `function-definition` scope as below solves your issue
> 
> ### In here
> ```json
> "function-definition": {
>     "comment": "Funtion program unit. Introduced in the Fortran 1977 standard.",
>     "name": "meta.function.fortran",
>     "begin": "(?i)(?=([^'\";!\\n](?!\\bend))*\\bfunction\\b)",
>     "end": "(?=[;!\\n])",
> ```
> 
> ### Change
> ```json
>     "begin": "(?i)(?=([^'\";!\\n](?!\\bend))*\\bfunction\\b)",
> ```
> 
> ### To
> ```json
>     "begin": "(?i)(?=([^'\";!\\n](?!\\bend))*^\\s*\\bfunction\\b)",
> ```
> 
> If it works, please consider adding the same fix to `subroutine-definition` in the same PR.

I think I might need to do some more work at escaping keywords because `character(kind=c_char, len=function_len) :: function` still seems to be wrong. I will have a look.

**Comment by gnikit** [comment]
This has now been fixed. The solution was a bit more involved than what I originally stated but should be okay now.
