### ISSUE TITLE
Add `What's New` part in version Releases

### ISSUE THREAD

**Issue by gnikit** [fortran-lang/vscode-fortran-support#465]
**Is your feature request related to a problem? Please describe.**
Add a markdown syntax file to highlight the main changes in a release.

My solutions are:
1. have a local markdown file that will be shipped around for each release, pop-up shows taking you to file
2. create a Wiki page for each release and have a pop-up take you the page.

**Comment by bilderbuchi** [comment]
@gnikit is this display of the release notes configurable? I'm using a remote development container, and every time I rebuild it, this "What's new" file pops up again. Would be great if I could switch this off in the VSCode settings specific to the container.

**Comment by gnikit** [comment]
No it's not at the moment, the justification being that we have to inform the users about the changes every time the extension is installed. I will add an option to disable it in a future release.
