### ISSUE TITLE
Highlight of ERROR STOP

### ISSUE THREAD

**Issue by han190** [fortran-lang/vscode-fortran-support#486]
Hi, thanks for the great work! I have a little issue here regarding to the `error stop` statement.

If I use an character variable instead of an actual string after `error stop`, it will be highlighted as invalid. The corresponding textmate scope is `invalid.error.character.fortran`. I am not sure if this is reproducible on other computers, but on my laptop it appears even in the simplest case (like the image shown below).

![image](https://user-images.githubusercontent.com/13799118/169615870-a26b45a3-e649-4234-8796-6a29ef3f0a74.png)

I think this issue is related to the regex definition of `"error-stop-statement"` in the `json` file,
https://github.com/fortran-lang/vscode-fortran-support/blob/0f58f1d553db654d2b22ed0c2ea72f7ceac8f052/syntaxes/fortran_free-form.tmLanguage.json#L2189

where only `"#constants"` and `"#string-operators"` are allowed after `error stop`. Apparently, it is difficult for the regex definition to capture all _scalar character constant expressions_ and _scalar integer constant expressions_. Since I know you are also the author of `fortls` (Great work and thanks again!), I wonder if it is possible to use fortls instead of a regex definition to highlight what comes after `error stop`?

**Comment by gnikit** [comment]
Thanks for the report @han190. I think I might be able to relax the constraint a bit to include variables, if I recall correctly I was just lazy to pull up the Fortran standard to see what values are allowed for the stop message.

As for the fortls + TM syntax highlighting see this issue, https://github.com/gnikit/fortls/issues/56

Basically I need to make some changes to the AST scopes internally in `fortls` to match the textmate grammar

**Comment by han190** [comment]
Nice, @gnikit thanks for the reply. If `fortls` and textmate match perfectly, it will be possible to write a Fortran-aware color theme.
