### ISSUE TITLE
[FEAT] Colorized brackets for if and do blocks

### ISSUE THREAD

**Issue by blaylockbk** [fortran-lang/vscode-fortran-support#525]
### Is there an existing request for this?

- [X] I have searched the existing issues

### Feature Request

First, thanks for this awesome Fortran extension! It has helped me in so many ways these last few years. 

This idea might be somewhat related to syntax highlight and code folding (https://github.com/fortran-lang/vscode-fortran-support/issues/135). 

VS Code's colorized brackets feature is really helpful, and it would be nice if that was extended to conditional statements and loops. This might be a bit hacky, but in my `settings.json` I applied the colorized bracket behavior on Fortran code for `if` and `do` statements.

```json
"[FortranFreeForm]": {
    "editor.language.colorizedBracketPairs": [
      ["(", ")"]
      ["[", "]"]
      ["{", "}"]
      ["if", "end if"],
      ["do", "end do"],
    ]
  },
```
This enables colorized brackets on the if blocks and do loops and makes it easy to see where each block start and end.

![image](https://user-images.githubusercontent.com/6249613/173117833-27485da1-f0fc-49de-adee-a4bcf1ca4931.png)

However, this doesn't work for all cases, like a one-line `if`. Here, the first `if` is highlighted red because there isn't a matching `end if` and the following blocks are not colorized.
![image](https://user-images.githubusercontent.com/6249613/173113704-85bdfe0c-cc9a-4cc4-ac19-c31eed00dfe6.png)

I realize there are other complexities with this feature, but I wondered if colorized brackets on if and do statements could be applied alongside code folding.

**Comment by gnikit** [comment]
Thanks for the request. I think what you are suggesting falls slightly outside of the scope of this extension and closer to a vscode theme.

The way that this would be implemented would be by creating a theme where it colours the scope names with the same colour as the brackets.

You can get the scope names from the developer scope tool within VScode.

**Comment by blaylockbk** [comment]
Ok, Thanks! I'll look into this.

**Comment by gnikit** [comment]
Okay, since this falls outside of the scope of this extension, I will be closing this issue. Feel free to start a [Discussion](https://github.com/fortran-lang/vscode-fortran-support/discussions) if you have any more questions.
