### ISSUE TITLE
C type comment for Fortran77

### ISSUE THREAD

**Issue by ekritikos** [fortran-lang/vscode-fortran-support#535]
### Is there an existing request for this?

- [X] I have searched the existing issues

### Feature Request

Hello,

I am using Fortran 77 which recognizes as a comment a C character in the first column. Is it possible to configure the editor so that when I press "Ctrl+/" C characters are inserted at the first column instead of exclamation marks?

Thank you very much!

**Comment by gnikit** [comment]
Thanks for the request, this is quite simple to do. Ass we need to add is a configuration file. I actually implemented this many months back but ended up removing the feature before release because I couldn't think of an easy way to maintain both the free and fixed configuration files.

I think it's alright for now, our configuration is not that elaborate so we can just manually maintain it.

**Comment by ekritikos** [comment]
That sounds great. Would you mind sharing this configuration file? Or is it in a different branch?

Thanks a lot!

**Comment by gnikit** [comment]
I will release a minor release now. Give me 10' tops.

**Comment by gnikit** [comment]
Actually, I just remembered why I didn't release the feature. It had to do with the fact that inline comments in Fixed Form Fortran are still marked by `!`, so technically speaking you would want to have the comment character that works for both full lines and inlines.

```f77
c      Start expression analyzer 
       CHARACTER S, STACK*80 
       COMMON /PRMS/ N, S, STACK 
       ... 
*      Crack the expression:
       IF ( S .GE. '0' .AND. S .LE. '9' ) THEN ! EoL comment 
              CALL PUSH        ! Save on stack. EoL comment 
d             PRINT *, S       ! Debug comment & EoL comment 
       ELSE 
              CALL TOLOWER ! To lowercase EoL comment 
       END IF 
D      PRINT *, N!       Debug comment & EoL comment 
       ... 
C      Finished 
!       expression analyzer
```

**Comment by ekritikos** [comment]
I see. So there isn't a possibility to recognise as comment both "C" and "!", but when pressing Ctrl+/ to input only C?

**Comment by gnikit** [comment]
Not that I am aware of. There is an open issue on the vscode repo about this: https://github.com/microsoft/vscode/issues/64659
Make sure to upvote it if you want to see this come in. There might be another way to do this but for that I will have to ask the VS Code team

**Comment by ekritikos** [comment]
Thanks a lot!
