### ISSUE TITLE
[MAINT] Removed unused Language Aliases

### ISSUE THREAD

**Issue by gnikit** [fortran-lang/vscode-fortran-support#536]
Remove unused language aliases and add tags. Also, need to change the language alias `Fortran` from Fixed Form to Free Form. Changes that need to be made are as follows:

### Removed

- FORTRAN77
- fortran_fixed-form

### Changed

- `Fortran`: to F90 from F77. Is now the primary alias for FreeForm
- `Fortran77`: default alias for FixedForm

### Added

- Modern Fortran
- fortls
- fpm

----

This will cause breaking changes to anyone using the aliases instead of the language IDs. We will keep `Fortran90` as an alias for `FortranFreeForm` to keep things consistent with `fortls`.

**Comment by nassaralnassar1** [comment]
Thank you
