### ISSUE TITLE
[BUG] `linter.modOutput` not working for Intel compilers

### ISSUE THREAD

**Issue by gnikit** [fortran-lang/vscode-fortran-support#538]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Module output flag for Intel compilers is not working, thus .mod files are output in the source file directory.

### Expected Behaviour

`-module outputModDir` to result into .mod files being output into `outputModDir` instead of source root.

### Version of Modern Fortran

v3.1.0

### Version of Visual Studio Code

v1.69.0-insider, fbf1cf3832d43088e27837dbb68d24ab65a098c1

### Platform and Architecture

Linux x64 5.4.0-120-generic

**Comment by avysk** [comment]
It still does not work with `ifort` on Windows. I have `f90` file in `src` subfolder; my linter mod output is set to `${workspaceFolder}\build`. If I choose `gfortran` as linter, mod file goes into `build` and if I choose `ifort` then the mod file is generated right next to the source.

Modern Fortran 3.2.0, VSCode 1.79.1, Windows 11, though you probably do not need it. Notice:
```
❯ ifort -module foo
[...blah...]
ifort: command line warning #10155: ignoring option '/module'; argument required
[...blah...]
```
On Windows the right incantation is `-module:foo` with `:`.

**Comment by avysk** [comment]
I did not check but I suspect that it may apply to include path as well.

**Comment by gnikit** [comment]
Please post the **relevant details**, like versions of the extension, and vscode and vscode settings.

**Comment by avysk** [comment]
I believe I did post the versions of extension and VSCode, didn't I? What exactly VSCode settings do you need?

**Comment by avysk** [comment]
I believe I did post the versions of extension and VSCode. What VSCode settings do you need?

**Comment by avysk** [comment]
You do pass `-module foo` to `ifort`, don't you? It ignores such an option. How installing pre-release vscode might help?
```
❯ ag fortran C:\Users\alexe\AppData\Roaming\Code\User\settings.json
209:  "fortran.formatting.formatter": "fprettify",
210:  "fortran.formatting.fprettifyArgs": ["-l", "80"],
211:  "fortran.fortls.maxLineLength": 80,
212:  "fortran.fortls.maxCommentLineLength": 80,
213:  "fortran.fortls.nthreads": 8,
214:  "fortran.linter.includePaths": ["${workspaceFolder}\\build"],
216:  "fortran.linter.modOutput": "${workspaceFolder}\\build",
```

No local settings.

**Comment by gnikit** [comment]
There have been multiple bug fixes and features added since the last official release. All these are included in the pre-release of the extension.

**Comment by avysk** [comment]
Ah, I misunderstood you. Pre-release of the **extension** not vscode. Will try today.

**Comment by avysk** [comment]
Exactly the same behaviour with pre-release extension v3.4.2023053001. Not a big surprise, as you still pass `-module<SPACE>` to `ifort` and it does not work on Windows. Let me quote the extension output: `[INFO - <time>] [build.single] Compiler query command line: <path to ifort.exe> -syntax-only -fpp -warn all -module<SPACE><blah...>`. This is wrong on Windows.

**Comment by gnikit** [comment]
This issue is seems to be its own separate thing, it is now tracked in https://github.com/fortran-lang/vscode-fortran-support/issues/919. I will have to rethink the Linter interfaces, since I don't want to make a hack fix.

PS I was always under the impression that even though the Intel docs say to use `/module:` you could always pass the UNIX equivalent and it would silently work.

Support for Windows should be improving in the next major release (which is hopefully soon), since I am adding tests and improving the Python tool interactions.

**Comment by avysk** [comment]
You indeed can pass `-blah` instead of `/blah` but if the option requires a parameter `:` is required: `-blah:param`.

**Comment by avysk** [comment]
If it will be needed, I can help with testing things on Windows.
