### ISSUE TITLE
Confusing scoping of variable

### ISSUE THREAD

**Issue by Koushikphy** [fortran-lang/vscode-fortran-support#540]
Let's check this simple code
```fortran
module mod1
    implicit none
    private
    integer :: x = 10
end module mod1


program name
    use mod1 
    implicit none
    call test()
    contains 
    subroutine test()
        integer :: x
        print *, x
    end 
end program name
```

Now for this code, the linter shows warning (for the declaration statement inside that subroutine)
```
Variable "x" masks variable in parent scope
```
But the `x` in the module is private, so the subroutine declaration should not mask anything. Am I missing something here or is it a bug?

**Comment by gnikit** [comment]
This diagnostic is from the Language Server (i.e. [fortls](https://github.com/gnikit/fortls)) not the VS Code extension. Also, I was unable to replicate this. The only diagnostics I am getting is from the linter about the unused variable. If you could migrate this issue to the correct repo as a Q&A Discussion I would appreciate that.
