### ISSUE TITLE
[SYNTAX] Issue distinguishing between "real" type and "real" function

### ISSUE THREAD

**Issue by ChrisspyB** [fortran-lang/vscode-fortran-support#597]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The syntax highlighter struggles to distinguish between when `real` is used as a function (i.e. for casting) and when it used to declare the variable type. See screenshot below.

### Screenshots

![image](https://user-images.githubusercontent.com/8879093/182279112-342061bd-177d-4a13-99e0-1f66ad69e60e.png)
On line 4: The first `real` is pink (like the type declaration on line 3) and the rest are blue (like functions). Ideally, they would all be the same. Additionally, the first plus operator is not highlighted. 

### Code Example

```Fortran
program main
    integer :: a, b, c
    real :: x
    x = real(a) + real(b) + real(c)
end program main
```

### Fortran Version (Free/Fixed Form)

Free Form e.g. F90+

### Version of Modern Fortran

v3.2.0

### Version of Visual Studio Code

v1.67.2

### Platform and Architecture

Linux

**Comment by gnikit** [comment]
Thanks @ChrisspyB, we are aware of this. For it to be resolved would have to implement semantic tokens in our language server, which I am hoping to get to at some point. We already have the semantic tokens (that's how the language server works) we just need to communicate them to VS Code.

You can follow this issue on #478

**Comment by ChrisspyB** [comment]
I see, thank you. Apologies for the duplicate, it was not obvious to me that 478 had a similar root cause.
