### ISSUE TITLE
feat: Support VSCode Sticky Scroll feature

### ISSUE THREAD

**Issue by plevold** [fortran-lang/vscode-fortran-support#647]
### Is there an existing request for this?

- [X] I have searched the existing issues

### Feature Request

I suspect this might be related to fortls, but I'm rather clueless on the exact details at play here. Feel free to close/move the issue if fortls is the appropriate place to address this.

VSCode recently added a neat way of visualizing the current scope the code you're looking at is in. It's called Sticky Scroll and basically shows the lines declaring the relevant new scopes/types/functions/namespaces/etc that otherwise would be outside the screen: https://code.visualstudio.com/updates/v1_71#_sticky-scroll

Unfortunately this does not seem to work with Fortran code at the moment.

**Comment by gnikit** [comment]
I think this is a vscode feature so it should be working without us having to do anything, see

https://user-images.githubusercontent.com/16143716/188838623-c524cd1b-d5dc-444c-a5a3-410618c4d2dd.mp4

**Comment by plevold** [comment]
I see now that I must have tested with the feature turned off or before fortls was initialized because it does indeed work nicely with Fortran code as well:
![image](https://user-images.githubusercontent.com/10157556/188874467-013dd22a-920d-4811-8d56-0799b1b52fea.png)

Sorry about the mistake!

**Comment by gnikit** [comment]
No worries @plevold, glad you were able to fix this.
