### ISSUE TITLE
feat: option to disable Release notes

### ISSUE THREAD

**Issue by gnikit** [fortran-lang/vscode-fortran-support#675]
@gnikit is this display of the release notes configurable? I'm using a remote development container, and every time I rebuild it, this "What's new" file pops up again. Would be great if I could switch this off in the VSCode settings specific to the container.

_Originally posted by @bilderbuchi in https://github.com/fortran-lang/vscode-fortran-support/issues/465#issuecomment-1257987227_

**Comment by bilderbuchi** [comment]
Wow, so quick, thanks!
