### ISSUE TITLE
bug: wrong identation

### ISSUE THREAD

**Issue by as-92** [fortran-lang/vscode-fortran-support#760]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Auto identation in one-line do loop is wrong:

```
  do ic=1,2
    c(ic) = 0
  end do
  call xxx        ! normal identation
 
  do ic=1,2; c(ic) = 0; end do
    call xxx       ! additional wrong spaces in this case
```

### Expected Behaviour

I expect the formatter to recognize the end of the loop, even if it is on the same line
```
  do ic=1,2; c(ic) = 0; end do
  call xxx       ! beginning in the same position
```

### Version of Modern Fortran

v3.4.2022112801

### Version of Visual Studio Code

v1.73.1

### Platform and Architecture

Ubuntu 20.04 Linux x64 5.15.0-53-generic

### Additional Information

I use findent with following parameter:

"fortran.formatting.findentArgs": [
  "-i2"
]

**Comment by gnikit** [comment]
Hi @as-92, please report bugs for findent to the findent repo: https://github.com/wvermin/findent
