### ISSUE TITLE
bug: fprettifyArgs are ignored

### ISSUE THREAD

**Issue by mthcrts** [fortran-lang/vscode-fortran-support#787]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The arguments defined by `formatting.fprettifyArgs` are not passed on the command line.

I think that the `formatter` property is not initialized.

This patch should fix it:

```diff
diff --git a/src/features/formatting-provider.ts b/src/features/formatting-provider.ts
index bd9073b..027bed2 100644
--- a/src/features/formatting-provider.ts
+++ b/src/features/formatting-provider.ts
@@ -113,7 +113,8 @@ export class FortranFormattingProvider implements vscode.DocumentFormattingEditP
    * @returns {string[]} list of additional arguments
    */
   private getFormatterArgs(): string[] {
-    const args: string[] = this.workspace.get(`formatting.${this.formatter}Args`, []);
+    const formatterName: string = this.getFormatter();
+    const args: string[] = this.workspace.get(`formatting.${formatterName}Args`, []);
     return args;
   }

```

This fix is a workaround about that the `.fprettify.rc` file is not found.

Thanks for the work on this extension!

### Expected Behaviour

The arguments should be passed on the command line.

### Version of Modern Fortran

v3.2.0

### Version of Visual Studio Code

v1.74.2

### Platform and Architecture

Linux

**Comment by mthcrts** [comment]
Hmm, just now, I tried to pass `--config-file=` and it is actually passed!

I'm checking that...

**Comment by mthcrts** [comment]
Ok, I think I understand: the `formatter` property is only set in by `getFormatter()`, that is only called by `provideDocumentFormattingEdits`.
I suppose that this last function is only called at initialization.

So, it is necessary to restart VSCode to take the changes from `settings.json`.

**Comment by mthcrts** [comment]
closed

**Comment by mthcrts** [comment]
bis

**Comment by gnikit** [comment]
From the looks of it this seems to not be a bug, I will be closing it. Feel free to reopen.
