### ISSUE TITLE
bug: findent not found even though it is installed and in path (even specified it manually in settings)

### ISSUE THREAD

**Issue by sudokit** [fortran-lang/vscode-fortran-support#839]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I get this popup every time i save a fortran file. I clicked the install button. Nothing changed. I installed it manually and added to the settings as formatter path. 

```
[INFO - 4:56:06 PM] [format] Formatter located in: C:\ProgramFiles\miniconda\bin\findent.exe
[INFO - 4:56:06 PM] [format] Formatter located in: C:\ProgramFiles\miniconda\bin\findent.exe
[WARN - 4:56:06 PM] [format] findent not found! Attempting to install now.
```
(I tried using pre-release and nothing changed)

### Screenshots

![image](https://user-images.githubusercontent.com/64897647/223146532-0e3ed477-0398-44a6-8eb8-339558c7d4fc.png)

### Expected Behaviour

The extension to be satisfied with the executable i provided it.

### Version of Modern Fortran

3.4.0

### Version of Visual Studio Code

1.76.0

### Platform and Architecture

Windows

**Comment by gnikit** [comment]
Can you please  post the relevant vscode settings

**Comment by sudokit** [comment]
Related to the fortran extension?
Here are the only settings iv changed:
```  
"fortran.linter.compilerPath": "C:\\msys64\\mingw64\\bin\\gfortran.exe",
"fortran.formatting.path": "C:\\ProgramFiles\\miniconda\\bin\\findent.exe"
  ```

**Comment by sudokit** [comment]
Ooh okay. Sorry it probably was written somewhere in the docs. Thanks!
