### ISSUE TITLE
bug(syntax): Can't Suppress `Variable ... masks variable in parent scope' error

### ISSUE THREAD

**Issue by amam3214** [fortran-lang/vscode-fortran-support#981]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I want to suppress the warning shown in the following figure:
![image](https://github.com/fortran-lang/vscode-fortran-support/assets/72937037/96e39e62-0e56-4258-b666-ffaf778b8a42)

These are my the extra args in the linter settings:
![image](https://github.com/fortran-lang/vscode-fortran-support/assets/72937037/73d49756-5245-4772-b2dd-a824cdeca675)

Thanks!

### Screenshots

![image](https://github.com/fortran-lang/vscode-fortran-support/assets/72937037/96e39e62-0e56-4258-b666-ffaf778b8a42)
![image](https://github.com/fortran-lang/vscode-fortran-support/assets/72937037/73d49756-5245-4772-b2dd-a824cdeca675)

### Code Example

```Fortran
module my_module
  implicit none
  integer :: i, j, k

contains

subroutine my_sub(i,j)
  implicit none
  integer, intent(in) :: i
  integer, intent(out) :: j

  ! implementation of my_sub

end subroutine my_sub

end module my_module
```

### Fortran Version (Free/Fixed Form)

Free Form e.g. F90+

### Version of Modern Fortran

v3.2.0

### Version of Visual Studio Code

v1.80.2

### Platform and Architecture

Windows

**Comment by gnikit** [comment]
This warnings are generated by [fortls](https://github.com/fortran-lang/fortls) not the vscode extension itself.
At this point there is not way to enable/disable individual diagnostics, you can disable all the diagnostics emitted from forts by adding to the `fortls` options in vscode the `--disable_diagnostics` flag.
In the pre-release of the VS Code extension you can easily do that with the option

```json
"fortran.fortls.disableDiagnostics": true,
```

For everything else have a look at the `fortls` configuration [documentation](https://fortls.fortran-lang.org/options.html#:~:text=%2D%2Ddisable_diagnostics) and add either a configuration file with this option or edit the command line arguments passed into vscode directly.
