### ISSUE TITLE
bug: Intel Fortran Linting Generates Preprocessed output to source directory

### ISSUE THREAD

**Issue by dnwillia-work** [fortran-lang/vscode-fortran-support#991]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the extension is configured to use Intel Fortran (on windows) it generates the preprocessed Fortran output into the source directory alongside my code.  So, for instance if I have the following:

`src/my_module.f90`

and I load that into the editor, after the linter runs on my code I see:

`src/my_module.f90`
`src/my_module.i90`

I'm manually adding the `/nofpp` option to the linter arguments to deactivate this output.

Is it doing this by default for some reason?

### Expected Behaviour

I would expect that the preprocessed `.i90` files are not generated into my source tree.

### Version of Modern Fortran

v3.2.0

### Version of Visual Studio Code

v1.82

### Platform and Architecture

Windows

**Comment by gnikit** [comment]
Enabling the preprocessor parsing is pretty standard in projects, so it will be on by default.
What is not normal is the behaviour you described. This has been a known issue for a long time, but unfortunately it lies on the Intel compiler side and not the vscode extension.
For more, you can follow the discussion on https://fortran-lang.discourse.group/t/annoying-i90-i-files-when-using-ifort-compiler/4716

**Comment by andershol** [comment]
@gnikit At the link you specified one commenter says (and this is also what I observe) that the temp files are created in the working folder. So couldn't you use a temp-folder, which you can clean up afterwards, as the working folder when invoking ifort? To me it seems like a rather clean workaround.

**Comment by dnwillia-work** [comment]
Yeah, ok.  So, I think what I was suggesting is that the linter could be running `/nofpp` by default.  Having the preprocessed source in the same directory as the original source was messing things up.
